(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var F4=function(a){a.ma("cardstatechange",a.Ii()&&a.Gm()?1:0)},G4=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},y3a=function(a){var b=g.Kl(a);
a=g.Nl(a);return new g.zl(b.x,b.y,a.width,a.height)},z3a=function(a){return Math.pow(a,3)},A3a=function(a){return 3*a*a-2*a*a*a},J4=function(a){a=g.Na(a);
delete H4[a];g.vf(H4)&&I4&&I4.stop()},C3a=function(){I4||(I4=new g.bo(function(){B3a()},20));
var a=I4;a.isActive()||a.start()},B3a=function(){var a=g.Qa();
g.hf(H4,function(b){D3a(b,a)});
g.vf(H4)||C3a()},K4=function(a,b,c,d){g.xo.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},D3a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;E3a(a,a.progress);1==a.progress?(a.j=0,J4(a),a.onFinish(),a.qA()):a.Qc()&&a.LF()},E3a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},F3a=function(a,b){g.bf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},L4=function(a,b,c,d,e){K4.call(this,b,c,d,e);
this.element=a},G3a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
L4.call(this,a,b,c,d,e)},M4=function(a){g.L.call(this);
this.u=a||window;this.j=[]},N4=function(a){return a.baseUrl||null},O4=function(a,b){return g.Am(g.Mk(a,b),function(c){return!!c})},H3a=function(a,b,c){function d(W){var ea=W.hovercardButton;
if(!ea)return null;ea=ea.subscribeButtonRenderer;if(!ea)return null;var P=f(ea.unsubscribedButtonText),za=f(ea.subscribedButtonText);if(ea.subscribed){var ya=f(ea.subscriberCountWithUnsubscribeText);var Ea=f(ea.subscriberCountText)}else ya=f(ea.subscriberCountText),Ea=f(ea.subscriberCountWithSubscribeText);var Da=null;if(W.signinEndpoint){Da=G4(W,"signinEndpoint","webNavigationEndpointData","url");if(!Da){var Ja,sa,va;Da=null==(Ja=ea.signInEndpoint)?void 0:null==(sa=Ja.commandMetadata)?void 0:null==
(va=sa.webCommandMetadata)?void 0:va.url}if(!Da)return null}return P&&(za||Da)?{subscribed:ea.subscribed,subscribeText:P,subscribeCount:ya,unsubscribeText:za,unsubscribeCount:Ea,enabled:ea.enabled,signinUrl:Da,classic:W.useClassicSubscribeButton}:null}
function e(W){if(W){var ea=[],P=W.videoId;P&&ea.push("v="+P);(P=W.playlistId)&&ea.push("list="+P);(W=W.startTimeSeconds)&&ea.push("t="+W);return"/watch?"+ea.join("&")}}
function f(W){if(!W)return null;var ea=W.simpleText;return ea?ea:W.runs?g.Mk(W.runs,function(P){return P.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,y=null,z=!1,B=null,D=null,G=null,E=null,I=null,K=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(K=l.watchEndpoint,m=e(K)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(K=l.watchEndpoint,m=e(K)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(z=G4(l,"browseEndpoint","browseId"))y=z,m="/channel/"+y;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((G=G4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=G4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=G4(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:
null,U="";if(b.metadata){var Q=f(b.metadata);Q&&(U=Q)}return{id:"element-"+c,type:h,title:f(b.title),metadata:U,callToAction:f(b.callToAction),aP:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:D,isSubscribe:z,targetUrl:m||null,c_:n,sessionData:M?{itct:M}:null,a4:q,Cy:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:O4(b.impressionUrls||[],N4),RZ:O4(b.hovercardShowUrls||[],N4),clickUrls:O4(l.loggingUrls||[],N4),visualElement:g.zz(b.trackingParams),productPrice:E,additionalFeesText:I,watchEndpoint:K||null}},I3a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O4(a.impressionUrls||[],N4),elements:O4(a.elements||[],function(d,e){return H3a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.zz(a.trackingParams));return c},J3a=function(a){g.NO.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.T=g.kG(a)||g.oG(a);this.ea=a.experiments.gb("web_rounded_thumbnails");this.events=new g.mE(this);g.N(this,this.events);this.events.S(this.player,g.yA("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.zA("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Ab);this.events.S(window,"focus",this.U2);this.load();var b=g.$g("STYLE");(g.Sg("HEAD")[0]||
document.body).appendChild(b);g.We(this,function(){g.eh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},K3a=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},P4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},L3a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=I3a(f,K3a(a))));Q4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Eu;d&&(c.postParams={ad_tracking:d});if(b=g.CCa(b))if(b=g.jg(b),b=g.dg(b))a.B=g.Ku(b,c)},Q4=function(a,b,c){c=void 0===c?!0:c;
a.player.xf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&M3a(a);c=[];d=new g.wA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.X({F:"div",N:"ytp-ce-shadow"}),g.hO(a.player,a.u.element,4),a.C=new g.jM(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=N3a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.hO(a.player,f.element,4);var h=new g.wA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);O3a(a,
f,e)}else g.wz(new g.Mv("buildEndscreenElement null",e))}a.player.me(c);a.Ab()}},M3a=function(a){var b=g.Fz(),c=g.Gz();
c&&b&&a.endscreen.visualElement&&g.Kz(void 0,c,b,[a.endscreen.visualElement])},N3a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ga:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Cy||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:R4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:S4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Bo(b.title||"")},qa:b.title},{F:"div",N:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={F:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Cy||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:R4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:S4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Bo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-playlist-count",
W:[{F:"div",N:"ytp-ce-playlist-icon"},{F:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={F:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Cy||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],X:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Bo(b.title||"")},qa:b.title},b.subscribeButton?{F:"div",N:"ytp-ce-subscribe-container",W:[{F:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{F:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:R4(b)}]};c=new g.X(c);var d=g.Tg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.lo(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.RP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ga:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Cy||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-website-title",X:{dir:g.Bo(b.title||"")},qa:b.title},{F:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],X:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:R4(b)},{F:"div",N:"ytp-ce-expanding-icon",X:P3a(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",N:"ytp-ce-merchandise-price-container",W:[{F:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={F:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Cy||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},
{F:"div",N:"ytp-ce-expanding-overlay-content",W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-merchandise-title",X:{dir:g.Bo(b.title||"")},qa:b.title},c,{F:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{F:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:R4(b)},{F:"div",N:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",N:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.lo(c.element,"ytp-ce-placeholder");return c},R4=function(a){if(a.aP)var b=a.aP.thumbnails;
return P3a(b?b[b.length-1].url:null)},P3a=function(a){return a?{style:"background-image: url("+a+")"}:{}},O3a=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.lo(b.element,"ytp-ce-force-expand"),T4(a,c.id,!0)):(g.no(b.element,"ytp-ce-force-expand"),g.no(b.element,"ytp-ce-element-hover"),T4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){Q3a(a,b,c)});
b.Qa("mouseleave",function(){R3a(a,b,c)});
a.player.V().isMobile||b.Qa("click",function(){g.lo(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){S3a(a,c,m)});
b.Qa("keypress",function(m){S3a(a,c,m)});
b.Qa("focus",function(){Q3a(a,b,c)});
b.Qa("blur",function(){R3a(a,b,c)});
b.Qa("touchstart",function(){Q3a(a,b,c)});
var l=g.Vg("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.no(b.element,"ytp-ce-element-hover");g.no(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.Vg("ytp-sb-subscribe",b.element));d(g.Vg("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},S3a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.ko(d,"ytp-ce-element");){g.ko(d,"subscribe-label")&&T3a(a,b);
if(g.ko(d,"ytp-ce-channel-subscribe"))return;d=g.fh(d)}if(!d||g.ko(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])R3a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.a4)T3a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.jg(S4(a,b.targetUrl)),g.LM(g.dg(c),void 0,b.sessionData);else{var e=g.FG(a.player.V())||a.player.getVideoData().D,f=function(){var h=S4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.wu(h);e&&n&&(n.v||
n.list)?a.player.Xl(n.v,l,n.list,!1,void 0,m||void 0):g.KM(h,l)};
T3a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.PG(a)+b}else return"";return b},Q3a=function(a,b,c){g.ko(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.lo(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.bo(function(){g.lo(b.element,"ytp-ce-element-hover")},200)).start():g.lo(b.element,"ytp-ce-element-hover"),U4(a,c.RZ),T4(a,c.id,!0))},R3a=function(a,b,c){g.no(b.element,"ytp-ce-element-hover");
g.no(b.element,"ytp-ce-force-expand");T4(a,c.id,!1)},T4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.po(a.j[e].element,"ytp-ce-element-shadow-show",c)},U4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P4(a))c&&c();else{b=U3a(a,b);var e=0,f=!1,h=new g.bo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.$w(b[a],d)}},T3a=function(a,b,c){U4(a,b.clickUrls,c);
(a=g.Gz())&&b.c_&&g.LK(a,b.visualElement)},U3a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(V3a(b[d],c));return a},V3a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},W3a=function(a){return"string"===typeof a?a:""},V4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},X3a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W4=function(a){return a.value?a.value:null},X4=function(a){if(!a)return null;
var b=g.jg(W3a(a.value));b=g.dg(b);if(!b)return null;var c=V4(a.target,Y3a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new X3a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Z3a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},b4a=function(a){if(!a)return null;
var b=V4(a.type,$3a),c=V4(a.trigger,a4a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X4(a?a:null);return b?new Z3a(b,c,a):null},c4a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},d4a=function(a,b){return g.Qb(a.action,b)},e4a=function(a,b){this.context=a;
this.j=b},f4a=function(a){return a.customMessage?Y4("div","iv-card-message",a.customMessage):""},Z4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",N:"iv-card-image",X:{style:a},W:c}},g4a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y4("li","",c.value));return{F:"ul",N:"iv-card-meta-info",W:b}},Y4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Bo(c);return{F:a,X:b,qa:c}},h4a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.My&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.My+");");c.dir=g.Bo(a.customMessage);var d=[{F:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",N:"iv-card-link-icon"}));return{F:"div",Ga:b,X:c,W:d}},$4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Mh.click,5)}},i4a=function(a,b){this.merchant=a;
this.price=b},j4a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},k4a=function(a,b){return b?b:j4a(a)?"current":"new"},a5=function(a,b){g.L.call(this);
var c=this;this.element=a;this.context=b;this.qb=!1;this.Wa=new Map;this.Xa=new Map;this.context.G.addEventListener(g.yA("annotations_module"),function(d){(d=c.Wa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.zA("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)})},b5=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.MF(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.qb=!1});
a.context.j.Qa(b,"touchmove",function(){a.qb=!0})},l4a=function(a){var b;
return(null==(b=g.R(a,g.iI))?0:b.url)?g.R(a,g.iI).url:(a=g.R(a,g.mH))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
qT:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
aF:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},m4a=function(a,b,c){a5.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Pa=this.Mb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Cb=this.T=this.La=this.D=this.Sa=this.j=null;this.ea=[];this.oa=this.J=this.uf=this.Ia=null;this.I=0;this.Ba=new g.bo(function(){},c.Y.Of?4E3:3E3);
g.N(this,this.Ba);this.kb=new g.bo(function(){});
g.N(this,this.kb);this.Aa=new e4a(c,function(e,f,h,l,m,n){b5(d,e,f,h,l,m,n)});
this.Z=new g.X({F:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",N:"iv-drawer-header-text"},{F:"button",Ga:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",N:"iv-drawer-content"}]});g.N(this,this.Z);this.C=this.Z.element;this.ib=new g.jM(this.Z,330);g.N(this,this.ib);this.Nb=g.Vg("iv-drawer-header-text",this.C);this.u=g.Vg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Mb&&d5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Mb=d.B)&&e5(d)});
this.G.addEventListener("videodatachange",this.wq.bind(this))},n4a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e5(a)});
var c=b.headerText;g.hh(a.Nb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.zz(b.trackingParams);a.J=g.zz(b.closeTrackingParams);a.uf=g.zz(b.iconTrackingParams)},o4a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.DA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Mh:{},Hm:null,Qj:e.trackingParams?g.zz(e.trackingParams):null,uf:f&&f.trackingParams?g.zz(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
My:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.DA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:g5(a,c,b,f),sponsored:!1,Mh:c5(f,e,f.command),Hm:f.trackingParams?g.zz(f.trackingParams):null,Qj:e.trackingParams?g.zz(e.trackingParams):null,uf:l&&l.trackingParams?g.zz(l.trackingParams):null,imageUrl:h5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.DA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,My:null,title:f.title?g.DA(f.title):"",customMessage:f.callToAction?g.DA(f.callToAction):"",url:g.R(f.command,g.iI).url?X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.iI).url}):null,onClickCommand:null};f5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.DA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Mh:c5(e,f,e.endpoint),Hm:e.trackingParams?g.zz(e.trackingParams):null,Qj:f.trackingParams?g.zz(f.trackingParams):null,uf:l&&l.trackingParams?g.zz(l.trackingParams):null,channelId:g.R(e.endpoint,i5).browseId,customMessage:e.customText?g.DA(e.customText):null,profileImageUrl:h5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.DA(e.channelName):"",metaInfo:[e.subscriberCountText?g.DA(e.subscriberCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,i5).canonicalBaseUrl?g.R(e.endpoint,i5).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,i5).browseId}),onClickCommand:null};f5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.DA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Mh:c5(e,f,e.action),Hm:e.trackingParams?g.zz(e.trackingParams):null,Qj:f.trackingParams?g.zz(f.trackingParams):null,uf:l&&l.trackingParams?g.zz(l.trackingParams):null,gB:h5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.DA(e.customMessage):null,playlistVideoCount:g.DA(e.playlistVideoCount),title:e.playlistTitle?g.DA(e.playlistTitle):"",metaInfo:[e.channelName?g.DA(e.channelName):
"",e.videoCountText?g.DA(e.videoCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:l4a(e.action)}),onClickCommand:null};f5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.DA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,Mh:c5(e,f,e.action),Hm:e.trackingParams?g.zz(e.trackingParams):null,Qj:f.trackingParams?g.zz(f.trackingParams):null,uf:l&&l.trackingParams?g.zz(l.trackingParams):null,gB:h5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.DA(e.lengthString):null,customMessage:e.customMessage?g.DA(e.customMessage):null,title:e.videoTitle?g.DA(e.videoTitle):"",metaInfo:[e.channelName?g.DA(e.channelName):
"",e.viewCountText?g.DA(e.viewCountText):""],isLiveNow:!!e.badge,url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:l4a(e.action)}),onClickCommand:null};f5(a,b)}}}}}a.I++},h5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},g5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},q4a=function(a,b){if(b=p4a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.eh(b.iH),g.ac(a.cards,b),a.iC(),j5(a)},d5=function(a,b,c){if(!a.B){a.ib.show();
a.Sa=new g.bo(function(){g.lo(a.context.G.getRootNode(),g.gU.IV_DRAWER_OPEN)},0);
a.Sa.start();a.ya=g.tx(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Gz();d&&a.Ia&&a.J&&g.JK(d,[a.Ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.MQ||(f.MQ=!0,r4a(a.context.logger,f.card.Mh.impression,b)),d&&g.JK(d,[f.card.Hm]);F4(a.G);c&&(a.D=new g.bo(function(){a.La=a.T;a.Cb.focus()},330),a.D.start())}},e5=function(a){a.B&&(a.ib.hide(),g.ux(a.ya),a.ya=null,g.no(a.context.G.getRootNode(),g.gU.IV_DRAWER_OPEN),a.B=!1,F4(a.G),a.D&&a.D.stop(),a.D=new g.bo(function(){a.La&&(a.La.focus(),a.La=null)},330),a.D.start())},
t4a=function(a){g.mo(a.element,[g.gU.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.hO(a.G,a.C,5);s4a(a);a.T=g.Vg("ytp-cards-button",a.G.getRootNode());a.Cb=g.Vg("iv-drawer-close-button",a.C);a.isInitialized=!0},s4a=function(a){var b=g.Vg("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.AY,a);a.context.j.Qa(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Qa(a.u,"scroll",a.MY,a);a.context.u.subscribe("onHideControls",function(){a.Pa=!0});
a.context.u.subscribe("onShowControls",function(){a.Pa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Pa=g.ko(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.Nx("iv-button-shown",a.l_,a));a.ea.push(g.Nx("iv-button-hidden",a.k_,a));a.ea.push(g.Nx("iv-teaser-shown",a.WU,a));a.ea.push(g.Nx("iv-teaser-hidden",a.m_,a));a.ea.push(g.Nx("iv-teaser-clicked",a.VU,a))},u4a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.R(b.onClickCommand,g.v0a))?void 0:c.targetId)?(a.oa=b,!0):!1},v4a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.R(h[0],g.R1a))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}}a.oa=b;return!1},f5=function(a,b){if(!u4a(a,b)||v4a(a,b)){var c=w4a(a,b);
if(c){var d={card:b,iH:c.element,MQ:!1};if(!b.onClickCommand){a.isInitialized||t4a(a);q4a(a,b.id);var e=x4a(a,d);g.gc(a.cards,e,0,d);c.Ca(a.u,e);a.iC()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,j5(a),y4a(a,d),d5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&z4a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){z4a(a,d)}),j5(a))}}},w4a=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{F:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=h4a(b);d={F:"div",Ga:["iv-card"],W:[{F:"a",N:"iv-click-target",X:{href:b.url?W4(b.url)||"":""},W:[Z4(b.imageUrl,d),{F:"div",N:"iv-card-content",W:[Y4("h2",void 0,b.title),e]}]}]};d=new g.X(d);$4(c,g.Ug("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-channel"],W:[{F:"a",Ga:["iv-click-target"],X:{href:W4(b.url)||"","data-ytid":b.channelId},W:[Z4(b.profileImageUrl),
{F:"div",N:"iv-card-content",W:[f4a(b),{F:"h2",N:"iv-card-primary-link",qa:b.title},g4a(b)]}]}]};d=new g.X(d);$4(c,g.Ug("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={F:"div",Ga:["iv-card","iv-card-playlist"],W:[{F:"a",N:"iv-click-target",X:{href:W4(b.url)||""},W:[Z4(b.gB,{F:"div",N:"iv-card-image-overlay",W:[{F:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{F:"div",N:"iv-card-content",W:[f4a(b),Y4("h2","iv-card-primary-link",b.title),g4a(b)]}]}]};
d=new g.X(d);$4(c,g.Ug("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.Vb(b.offers);d=["iv-card"];e="";var h=h4a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",N:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({F:"div",N:"iv-card-offer-merchant",qa:h.merchant}),h={F:"div",W:f});f=b.url?W4(b.url)||"":"";d={F:"div",Ga:d,X:{tabindex:"0"},W:[{F:"a",Ga:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",N:"iv-card-content",W:[b.sponsored?{F:"div",N:"iv-card-sponsored",W:["Sponsored",{F:"div",N:"iv-ad-info-container",W:[{F:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{F:"div",N:"iv-ad-info-icon-container",W:[{F:"div",N:"iv-ad-info-icon"},{F:"div",N:"iv-ad-info-callout"}]}]}]}:"",{F:"a",N:"iv-click-target",X:{href:f},W:[Y4("h2",e,b.title),h]}]}]};d=new g.X(d);e=g.$g("span");g.hh(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Pd(e,"adInfo");$4(c,g.Ug("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{F:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Ga:["yt-badge","yt-badge-live"],qa:"LIVE NOW"}:null;f={F:"div",Ga:["iv-card","iv-card-video"],W:[{F:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:W4(h))||""},W:[Z4(b.gB,d),{F:"div",N:"iv-card-content",W:[f4a(b),Y4("h2","iv-card-primary-link",b.title),g4a(b),e]}]}]};d=new g.X(f);$4(c,g.Ug("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.gb("web_rounded_containers")&&g.lo(b.element,"ytp-rounded-info");return b},x4a=function(a,b){if(0===a.cards.length)return 0;
a=g.Rb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},A4a=function(a){return a.j?"productListing"===a.j.card.type:g.Wd(a.cards,function(b){return"productListing"===b.card.type})},j5=function(a){g.po(a.G.getRootNode(),"ytp-cards-shopping-active",A4a(a))},z4a=function(a,b){if(!g.ko(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Gz(),d=a.j?a.j.card.uf:a.uf;
c&&d&&g.KK(c,[d]);a.j=b;j5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.kx(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.kb.isActive()||((!a.B||!a.Ba.isActive()&&a.Pa)&&y4a(a,b),a.kb.start(910+b.card.teaserDurationMs))}},y4a=function(a,b){a.Z.rb?(b=new K4([0,
a.u.scrollTop],[0,b.iH.offsetTop],600,A3a),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.wL(a.Z,!0),a.u.scrollTop=b.iH.offsetTop,g.wL(a.Z,!1))},k5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},p4a=function(a,b){return g.Qb(a.cards,function(c){return c.card.id===b})},l5=function(a,b,c){a5.call(this,a,b);
this.annotation=c;this.isActive=!1},B4a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m5=function(a,b,c){l5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},C4a=function(a,b){var c=void 0===c?0:c;
var d=y3a(b).width;g.Il(b,d);c=new G3a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,z3a);g.N(a,c);a.context.B.Qa(c,"begin",function(){g.Ol(b,!0)});
c.play()},F4a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({F:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.RP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ol(h,!1);a.context.Y.K("web_rounded_containers")&&g.lo(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.Cl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.bo(function(){D4a(a,h,l)},500);
g.N(a,a.B);a.context.j.Qa(a.element,"mouseover",function(){E4a(a,h,l,f,b.image_height)});
a.context.j.Qa(a.element,"mouseout",function(){a.B.start()})}},E4a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Nl(b);a.j||(b.style.width=g.Hl(f.width,!0),c.style.width=g.Hl(f.width,!0));g.Cl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Cl(d,"right","1px");a.C=!0;g.Ol(b,!0);a.D=new g.bo(function(){g.lo(this.element,"iv-branding-active")},0,a);
a.D.start()}},D4a=function(a,b,c){g.no(a.element,"iv-branding-active");
a.I=new g.bo(function(){g.Ol(b,!1);a.j||(c.style.width=g.Hl(0,!0))},250);
a.I.start();a.C=!1},G4a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},H4a=function(a,b,c){l5.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ga:["iv-promo-contents"]});this.D=new g.bo(function(){d.j.setAttribute("aria-hidden","true");g.Ol(d.B,!1);g.Ol(d.u,!0)},700,this);
g.N(this,this.D)},J4a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.Ae(),f=b.image_url;if(f){var h=a.createElement({F:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&b5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",N:"iv-promo-txt"}),g.tg(f,W4(e)),a.j=f):a.j=a.createElement({F:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",W:[{F:"strong",
qa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ga:["iv-button","iv-promo-button"],W:[{F:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({F:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&b5(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.lo(a.j,
"iv-click-target");e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",qa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"LIVE NOW"})),g.lo(a.j,"iv-click-target"),e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",N:"iv-promo-actions"});a.u=a.createElement({F:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Qa(a.u,"click",function(q){I4a(a,5E3,q)});
c.appendChild(a.u);g.Ol(a.u,!1);a.context.j.Qa(a.element,"mouseover",a.wZ,a);a.context.j.Qa(a.element,"mouseout",a.vZ,a);a.context.j.Qa(a.element,"touchend",function(q){I4a(a,5E3,q)});
a.B=a.createElement({F:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.rZ:a.qZ,a);c.appendChild(a.B);g.mo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},I4a=function(a,b,c){c.stopPropagation();
K4a(a);L4a(a,b);a.j.focus()},M4a=function(a){a.isCollapsed||a.T||a.C||(g.lo(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},K4a=function(a){a.D.stop();
a.isCollapsed&&(g.oo(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ol(a.u,!1),g.Ol(a.B,!0))},L4a=function(a,b){a.C||(a.C=g.Eh(function(){N4a(this);
M4a(this)},b,a))},N4a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},O4a=function(a){this.G=a},r4a=function(a,b,c){b&&(c?n5(a,b.map(function(d){return g.Vn(d,c)})):n5(a,b))},n5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.$w(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},P4a=function(a){g.NO.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new O4a(this.player);this.D=new g.mE(this);this.C=this.Mn=null;this.events=new g.mE(this);this.J=this.j=null;this.T=[];g.N(this,this.D);this.D.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.S(this.player,"resize",function(d){b.ma("resize",d)});
this.D.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.XU,this);this.subscribe("resize",this.YD,this);this.player.V().oa.subscribe("vast_info_card_add",this.ZR,this);g.N(this,this.events);this.Z=this.createElement({F:"div",N:"video-custom-annotations"});this.u=new g.X({F:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.N(this,this.u);g.hO(this.player,this.u.element,4);this.u.hide();this.B=new g.X({F:"div",Ga:["ytp-iv-video-content"]});g.N(this,this.B);a=this.createElement({F:"div",N:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Zt()&&this.load();var c=this.createElement({F:"style"});(g.Sg("HEAD")[0]||document.body).appendChild(c);g.We(this,function(){g.eh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Q4a=function(a){a=a.createElement({F:"div",
Ga:["annotation","annotation-type-custom"]});g.Ol(a,!1);return a},R4a=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.wL(a.u,b);g.wL(a.B,b)},S4a=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(S4a(a,e))}return c},W4a=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.V().oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Eu(h)&&h.responseXML?h.responseXML:null)&&T4a(a,h)}};
g.Kv()&&(d.onFinish=U4a(a,d.onFinish));d.postParams={ic_only:"1"};V4a(d,c);g.Ku(b.Wa,d)}}},V4a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Ny&&(a.postParams.ic_coll=b.Ny);b.oC&&(a.postParams.ic_xml=b.oC);b.jB&&(a.postParams.ic_track=b.jB)},X4a=function(a){var b=new g.X({F:"div"});
g.Ol(b.element,!1);var c=new m4a(a.player,b.element,o5(a));g.N(c,b);b.Ca(a.u.element);c.UA();return c},o5=function(a){if(!a.J){var b=new M4(a);
g.N(a,b);var c=new g.Lj(a);g.N(a,c);a.J=new G4a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Xg)}return a.J},T4a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Gz();if(e){var f=g.Fz();f&&g.Kz(void 0,e,f,[g.zz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=S4a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=V4(f.type,Y4a),p=V4(f.style,Z4a),q=W3a(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=b4a;if(null==w)var y=null;else if(g.Ka(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var D=f(B.value);
D&&l.push(D)}y=l}else{var G=f(w);y=G?[G]:[]}e=m&&n?new c4a(m,n,p,y,r):null}else e=null}catch(Q){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var E=Q4a(f),I=null;switch(l.type){case "branding":if(f.player.V().Pc)break;f.u.element.appendChild(E);I=new m5(E,o5(f),l);break;case "promotion":g.hO(f.player,E,4),I=new H4a(E,o5(f),l)}I&&I.UA();if(f=I)g.N(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=X4a(a),g.N(a,a.j));if("card"===e.type){c=a.j;var K=e&&e.data&&e.data.card_type;
f=e.data;if(K)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,qT:l.teaser_impression,aF:l.teaser_click},E=f.tracking_params||{},I=null,K){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mh:l,Hm:E.card?g.zz(E.card):null,Qj:E.teaser?g.zz(E.teaser):null,uf:E.icon?g.zz(E.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mh:l,Hm:E.card?g.zz(E.card):null,
Qj:E.teaser?g.zz(E.teaser):null,uf:E.icon?g.zz(E.icon):null,gB:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "productListing":f.signin_url&&(I=X4({target:"current",value:f.signin_url}));K=[];for(var M=f.offers||[],U=0;U<M.length;U++)K.push(new i4a(g.Mg(M[U].merchant),g.Mg(M[U].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mh:l,Hm:E.card?g.zz(E.card):null,Qj:E.teaser?g.zz(E.teaser):null,uf:E.icon?g.zz(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,My:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),g6a:I,f6a:f.signin_title?f.signin_title:void 0,e6a:f.signin_message?f.signin_message:void 0,offers:K,onClickCommand:null};f5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mh:l,Hm:E.card?g.zz(E.card):
null,Qj:E.teaser?g.zz(E.teaser):null,uf:E.icon?g.zz(E.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,My:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mh:l,Hm:E.card?g.zz(E.card):null,Qj:E.teaser?g.zz(E.teaser):null,uf:E.icon?g.zz(E.icon):null,gB:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},f5(c,e)}}else n4a(a.j,e);c=!0}}c&&
(F4(a.player),a.YD())},$4a=function(a,b){var c=!1;
a.j||(a.j=X4a(a),g.N(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(o4a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.DA(b.headerText):"",g.hh(c.Nb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.zz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.zz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.uf=b.icon.infoCardIconRenderer.trackingParams?
g.zz(b.icon.infoCardIconRenderer.trackingParams):null,F4(a.player),a.YD())},a5a=function(a,b,c,d,e){if(!a.player.V().Pc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Z3a("openUrl","click",new X3a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.DA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.DA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.DA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.DA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.DA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.DA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new c4a(c,"branding","branding",f,d);l=Q4a(a);a.u.element.appendChild(l);f=new m5(l,o5(a),f);f.UA();g.N(f,f);a.I[c]=f}},U4a=function(a,b){return function(){var c=
g.wa.apply(0,arguments);
a.isDisposed()||a.T.push(g.Yn.qj(function(){b.apply(null,g.u(c))}))}},b5a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.aO.prototype.kx=g.ba(19,function(a,b){var c=g.eP(this.tb());c&&c.kx(a,b)});
var H4={},I4=null;g.Ra(K4,g.xo);g.k=K4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Qc())return!1;J4(this);this.startTime=a=g.Qa();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.UD();this.vk("play");-1==this.j&&this.vk("resume");this.j=1;var b=g.Na(this);b in H4||(H4[b]=this);C3a();D3a(this,a);return!0};
g.k.stop=function(a){J4(this);this.j=0;a&&(this.progress=1);E3a(this,this.progress);this.vk("stop");this.qA()};
g.k.pause=function(){this.Qc()&&(J4(this),this.j=-1,this.vk("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.vk("destroy");K4.We.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.LF=function(){this.vk("animate")};
g.k.vk=function(a){this.dispatchEvent(new F3a(a,this))};
g.Ra(F3a,g.bf);g.Ra(L4,K4);L4.prototype.C=function(){};
L4.prototype.LF=function(){this.C();L4.We.LF.call(this)};
L4.prototype.qA=function(){this.C();L4.We.qA.call(this)};
L4.prototype.UD=function(){this.C();L4.We.UD.call(this)};
g.Ra(G3a,L4);G3a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var i5=new g.bp("browseEndpoint");g.v(M4,g.L);M4.prototype.Qa=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.tx(a,b,c);this.j.push(a);return a};
M4.prototype.DD=function(a,b,c,d){c=(0,g.Oa)(c,d||this.u);a=g.Moa(a,b,c);this.j.push(a);return a};
M4.prototype.xc=function(a){g.ux(a);g.ac(this.j,a)};
M4.prototype.ra=function(){g.ux(this.j);this.j.length=0;g.L.prototype.ra.call(this)};g.v(J3a,g.NO);g.k=J3a.prototype;g.k.load=function(){g.NO.prototype.load.call(this);if(!P4(this)){var a=g.DCa(this.player.getVideoData());a?(a=I3a(a,K3a(this)),Q4(this,a,!1)):L3a(this)}};
g.k.unload=function(){Q4(this,null);this.B&&(this.B.abort(),this.B=null);g.NO.prototype.unload.call(this)};
g.k.Gg=function(a,b){return P4(this)?"loadCustomEndscreenRenderer"===a?(a=I3a(b,"new"),Q4(this,a),!0):null:null};
g.k.getOptions=function(){return P4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ab=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<c5a.length;f++){var h=Math.abs(b.width-c5a[f]);if(-1===e||d>=h)e=f,d=h}d=d5a[e];this.u&&g.Cl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Ml(e.element,m,f);g.Il(e.element,n,p);this.ea&&(g.oo(e.element,e5a),256<m||256<f?g.lo(e.element,"ytp-ce-large-round"):96<m||96<f?g.lo(e.element,"ytp-ce-medium-round"):g.lo(e.element,"ytp-ce-small-round"));g.oo(e.element,f5a);m=h.left+h.width/2;h=h.top+l/2;g.lo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.oo(e.element,d5a);g.lo(e.element,d);(e=g.Tg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Cl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())U4(this,this.endscreen.impressionUrls),(a=g.Gz())&&this.endscreen.visualElement&&g.Lz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.lo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.lo(b,"ytp-ce-shown");U4(this,c.impressionUrls);(b=g.Gz())&&g.Lz(b,c.visualElement);this.player.V().D&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.no(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.no(b,"ytp-ce-shown");this.player.V().D&&this.player.Oa("endscreenelementhidden",a)}};
g.k.U2=function(a){var b=this;a.target===window&&(new g.bo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.oo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var c5a=[346,426,470,506,570,640,853,1280,1920],d5a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),f5a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],e5a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Y3a={yka:"current",wHa:"new"};var $3a={CLOSE:"close",XKa:"openUrl",SUBSCRIBE:"subscribe"},a4a={Bfa:"click",CLOSE:"close",aua:"hidden",jQa:"rollOut",kQa:"rollOver",iSa:"shown"};c4a.prototype.Ae=function(){var a=d4a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Z4a={oba:"anchored",vU:"branding",CHANNEL:"channel",oka:"cta",fua:"highlightText",Sxa:"label",PLAYLIST:"playlist",ONa:"popup",LUa:"speech",SUBSCRIBE:"subscribe",LXa:"title",VIDEO:"video",l3a:"website"},Y4a={vU:"branding",Fda:"card",Dma:"drawer",eua:"highlight",xDa:"marker",OOa:"promotion",TEXT:"text",V3a:"widget"};g.v(a5,g.L);g.k=a5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.wA(a,b,{id:c,namespace:"annotations_module"});d&&this.Wa.set(a,d);e&&this.Xa.set(a,e);this.context.G.me([a])};
g.k.UA=function(){this.context.u.subscribe("resize",this.iC,this)};
g.k.MF=function(a,b,c,d,e,f){if(this.qb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.eh(this.element)};
g.k.iC=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W4(a);if(f){var h=k4a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.wu(f||"");m&&n&&(n.v||n.list)?e.context.G.Xl(n.v,b,n.list,!1):g.LM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n5(this.context.logger,c,l,d);j4a(f)||(c=g.Gz(),d=b.itct,c&&d&&g.LK(c,g.zz(d)))}};
g.k.ra=function(){this.Wa.clear();this.Xa.clear();g.L.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.N(this,a);return a.element};g.v(m4a,a5);g.k=m4a.prototype;g.k.wq=function(){this.oa&&f5(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Nl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.iC=function(){var a=this.isAvailable();g.Ol(this.element,a);g.po(this.context.G.getRootNode(),g.gU.IV_DRAWER_ENABLED,a);F4(this.G)};
g.k.destroy=function(){this.G.kx(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Ox(this.ea);g.ux(this.ya);this.Sa&&this.Sa.dispose();this.D&&this.D.dispose();a5.prototype.destroy.call(this)};
g.k.AY=function(){if(this.B){n5(this.context.logger,k5(this).Mh.close);var a=g.Gz();a&&this.J&&g.LK(a,this.J);e5(this)}};
g.k.MY=function(){g.po(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.l_=function(){var a=g.Gz(),b=k5(this);b=b?b.uf:this.uf;a&&b&&g.JK(a,[b])};
g.k.k_=function(){var a=g.Gz(),b=k5(this);b=b?b.uf:this.uf;a&&b&&g.KK(a,[b])};
g.k.WU=function(){var a=k5(this);n5(this.context.logger,a.Mh.qT);var b=g.Gz();b&&a&&g.JK(b,[a.Qj,a.uf])};
g.k.m_=function(){var a=g.Gz(),b=k5(this);a&&b&&g.KK(a,[b.Qj])};
g.k.VU=function(a){var b=k5(this),c=g.Gz();this.j?a?(a=this.context.logger,n5(a,b.Mh.aF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Qj&&g.LK(c,b.Qj)):(a=this.context.logger,n5(a,b.Mh.aF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.uf&&g.LK(c,b.uf)):(a=this.context.logger,n5(a,b.Mh.aF),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.uf&&g.LK(c,this.uf))};g.v(l5,a5);l5.prototype.UA=function(){a5.prototype.UA.call(this);B4a(this)};
l5.prototype.show=function(){a5.prototype.show.call(this);var a=g.Gz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.JK(a,[g.zz(b.itct)])};
l5.prototype.hide=function(){a5.prototype.hide.call(this);var a=g.Gz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.KK(a,[g.zz(b.itct)])};g.v(m5,l5);
m5.prototype.show=function(){if(!this.isActive){l5.prototype.show.call(this);if(!this.J){g.lo(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ga:["branding-img","iv-click-target"],X:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ol(this.u,!1);var b=this.createElement({F:"button",Ga:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.Ae();c&&b5(this,
b,c,this.annotation.id,a.session_data);F4a(this,a);this.J=!0}g.Ol(this.element,!0);this.isActive=!0;this.u&&(C4a(this,this.u),g.lo(this.context.G.getRootNode(),"ytp-branding-shown"))}};
m5.prototype.hide=function(){this.isActive&&(l5.prototype.hide.call(this),g.Ol(this.element,!1),this.isActive=!1,g.no(this.context.G.getRootNode(),"ytp-branding-shown"))};
m5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l5.prototype.destroy.call(this)};g.v(H4a,l5);g.k=H4a.prototype;g.k.show=function(){this.isActive||(l5.prototype.show.call(this),this.Z||(J4a(this),this.Z=!0),g.Ol(this.element,!0),g.Eh(function(){g.no(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,N4a(this),K4a(this),L4a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.lo(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.MF=function(a,b,c,d,e,f){return this.isCollapsed?!1:l5.prototype.MF.call(this,a,b,c,d,e,f)};
g.k.wZ=function(a){this.T=!0;I4a(this,500,a)};
g.k.vZ=function(){this.T=!1;M4a(this)};
g.k.qZ=function(a){a.stopPropagation();this.hide()};
g.k.rZ=function(a){a.stopPropagation();N4a(this);this.isCollapsed=!0;g.lo(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();l5.prototype.destroy.call(this)};g.v(P4a,g.NO);g.k=P4a.prototype;g.k.Gg=function(a,b){if(!b5a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.UZa(b))&&T4a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(q4a(this.j,b),F4(this.player)),!0}return null};
g.k.getOptions=function(){return b5a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Zt=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.lM||a.oa.get(b.videoId)||g.II(b)||g.JI(b)?!0:!1};
g.k.YD=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.Ml(this.B.element,a.width,a.height);g.Il(this.B.element,a.left,a.top)}if(this.j){var b=this.player.wj();a=this.j;b=b.width;g.po(a.C,"iv-drawer-small",426>=b);g.po(a.C,"iv-drawer-big",1280<=b)}};
g.k.XU=function(a){R4a(this,a.state);g.V(a.state,2)&&(this.Ii()&&this.Gm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.kx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Eu(h)&&h.responseXML?h.responseXML:null)&&(T4a(b,h),g.lo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.NO.prototype.load.call(this);R4a(this,this.player.Db());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Kv()&&(a=U4a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().oa.get(d);f&&V4a(e,f);f=f&&(f.oC||f.Ny);if(!c.Nx||f)c.Wa?this.C=g.Ku(c.Wa,e):(this.Mn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Mn));
g.hO(this.player,this.B.element,4);this.YD();(f=g.II(c))&&$4a(this,f);(f=g.JI(c))&&f.featuredChannel&&a5a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&(this.Mn&&(this.player.removeEventListener("videodatachange",this.Mn),this.Mn=null),this.C=g.Ku(b.Wa,a))};
g.k.unload=function(){this.player.xf("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,F4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.NO.prototype.unload.call(this);this.B.detach();this.Mn&&(this.player.removeEventListener("videodatachange",this.Mn),this.Mn=null)};
g.k.ZR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?W4a(this):this.load())};
g.k.Ii=function(){return!!this.j&&this.j.isAvailable()};
g.k.Gm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ii();this.j&&(a?c?d5(this.j,c,b):d5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e5(this.j))};
g.k.kx=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().oa.unsubscribe("vast_info_card_add",this.ZR,this);g.no(this.player.getRootNode(),g.gU.IV_DRAWER_OPEN);for(var a=this.T,b=g.Yn,c=0,d=a.length;c<d;c++)b.ql(a[c]);this.T.length=0;g.NO.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.N(this,a);return a.element};g.MO("annotations_module",P4a);g.MO("creatorendscreen",J3a);})(_yt_player);
