(function(g){var window=this;'use strict';var e7a=function(a,b){a.Oa("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.po(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Cf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.lH&&(b.lengthText?(e=b.lengthText||null,f=b.ut||null):b.lengthSeconds&&(e=g.yM(b.lengthSeconds),f=g.yM(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.jH(d).type;var l=b instanceof g.lH?b.isLivePlayback:null,m=b instanceof g.lH?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.bK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Um(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.Mp};b instanceof g.kH&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.V(),c=b.B;
g.X.call(this,{F:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{F:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"Live"},{F:"div",
Ga:["ytp-autonav-upcoming-stamp"],qa:"Upcoming"},{F:"div",N:"ytp-autonav-list-overlay",W:[{F:"div",N:"ytp-autonav-mix-text",qa:"Mix"},{F:"div",N:"ytp-autonav-mix-icon"}]}]},{F:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{F:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.G=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{F:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.X({F:"div",N:"ytp-autonav-endscreen-countdown-container"});g.N(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.B;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.X({F:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{F:"div",N:"ytp-autonav-endscreen-upnext-header"},{F:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{F:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.T:""},W:[{F:"div",Ga:e,X:{style:"{{background}}"},W:[{F:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{F:"div",Ga:["ytp-autonav-live-stamp"],qa:"Live"},{F:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"Upcoming"}]},{F:"div",N:"ytp-autonav-endscreen-video-info",W:[{F:"div",N:"ytp-autonav-endscreen-premium-badge"},{F:"div",N:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{F:"div",N:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{F:"div",N:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},{F:"div",
N:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.N(this,this.j);this.j.Ca(this.container.element);d||this.S(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.DM);this.G.xb(this.container.element,this,115127);this.G.xb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({F:"div",N:"ytp-autonav-overlay"});g.N(this,this.overlay);this.overlay.Ca(this.container.element);this.u=new g.X({F:"div",N:"ytp-autonav-endscreen-button-container"});
g.N(this,this.u);this.u.Ca(this.container.element);this.cancelButton=new g.X({F:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel auto-play"},qa:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Ca(this.u.element);this.cancelButton.Qa("click",this.eV,this);this.G.xb(this.cancelButton.element,this,115129);this.playButton=new g.X({F:"a",Ga:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},qa:"Play now"});g.N(this,this.playButton);this.playButton.Ca(this.u.element);this.playButton.Qa("click",this.DM,this);this.G.xb(this.playButton.element,this,115130);this.C=new g.bo(function(){f7a(c)},500);
g.N(this,this.C);this.CM();this.S(a,"autonavvisibility",this.CM);this.G.K("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.dV),this.S(a,"onAutonavCoundownStarted",this.n0))},o6=function(a){var b=a.G.wj(!0,a.G.isFullscreen());
g.po(a.container.element,"ytp-autonav-endscreen-small-mode",a.pg(b));g.po(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.XE);g.po(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.jf());g.po(a.G.getRootNode(),"countdown-running",a.Aj());g.po(a.container.element,"ytp-player-content",a.G.jf());g.Cl(a.overlay.element,{width:b.width+"px"});if(!a.Aj()){a.G.jf()?g7a(a,Math.round(h7a(a)/1E3)):g7a(a);b=!!a.suggestion&&!!a.suggestion.Mp;var c=a.G.jf()||!b;
g.po(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.po(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.wL(a.u,a.G.jf());g.po(a.element,"ytp-enable-w2w-color-transitions",i7a(a))}},f7a=function(a){var b=h7a(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);g7a(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Aj()?a.select(!0):a.Aj()&&a.C.start()},h7a=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.aM;return-1===a||void 0===a?8E3:a}return 0<=a.G.hq()?a.G.hq():g.lF(a.G.V().experiments,"autoplay_time")||1E4},i7a=function(a){var b;
return!(null==(b=a.G.getVideoData())||!b.watchToWatchTransitionRenderer)},g7a=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.ch(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.bh("Up next in $SECONDS".slice(0,d)));var e=g.$g("span");g.io(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.hh(e,b);a.appendChild(e);a.appendChild(g.bh("Up next in $SECONDS".slice(d+c.length)));return}}g.hh(a,"Up next")},p6=function(a,b){g.X.call(this,{F:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.X.call(this,{F:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{F:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-upnext-top",W:[{F:"span",N:"ytp-upnext-header",qa:"Up Next"},{F:"span",N:"ytp-upnext-title",qa:"{{title}}"},{F:"span",N:"ytp-upnext-author",qa:"{{author}}"}]},{F:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{F:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{F:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",N:"ytp-upnext-bottom",W:[{F:"span",N:"ytp-upnext-cancel"},{F:"span",N:"ytp-upnext-paused",
qa:"Auto-play is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.bo(this.rC,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.X({F:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel auto-play"},qa:"Cancel"});g.N(this,this.cancelButton);this.cancelButton.Qa("click",this.fV,this);this.cancelButton.Ca(b);this.cancelButton&&this.api.xb(this.cancelButton.element,
this,115129);g.N(this,this.C);this.api.xb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.S(b,"click",this.gV);this.api.xb(b,this,115130);this.EM();this.S(a,"autonavvisibility",this.EM);this.S(a,"mdxnowautoplaying",this.W0);this.S(a,"mdxautoplaycanceled",this.X0);g.po(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},j7a=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.aM;return-1===a||void 0===a?8E3:a}return 0<=a.api.hq()?a.api.hq():g.lF(a.api.V().experiments,"autoplay_time")||1E4},k7a=function(a,b){b=j7a(a,b);
var c=Math,d=c.min;var e=(0,g.S)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Aj()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Aj()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.X({F:"div",N:"ytp-suggestion-panel",W:[{F:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"More videos"}]});this.J=new g.X({F:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new n6(this.player);g.N(this,this.u);this.u.Ca(this.element);a.getVideoData().Qe?this.j=this.u:(this.j=new q6(a),g.hO(this.player,this.j.element,4),g.N(this,this.j));this.overlay=new g.X({F:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.N(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.mE(this);g.N(this,this.C);g.N(this,this.table);this.table.Ca(this.element);this.table.show();g.N(this,this.J);this.J.Ca(this.table.element);this.hide()},s6=function(a){var b=a.jf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},t6=function(a,b){g.X.call(this,{F:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],X:{title:"{{message}}"},qa:"{{content}}"});this.G=a;this.buttonType=this.buttonType=b;switch(this.buttonType){case 1:a="Watch again on YouTube";b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({message:a,content:a});this.G.xb(this.element,this,b);this.Qa("click",this.onClick);g.wL(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.G=a;this.j=b;this.G.xb(this.element,this,156943);this.watchButton=new t6(a,2);g.N(this,this.watchButton);this.watchButton.Ca(this.element);this.hide()},l7a=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.X({F:"div",N:"ytp-subscribe-card",W:[{F:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{F:"div",N:"ytp-subscribe-card-right",W:[{F:"div",N:"ytp-author-name",qa:"{{author}}"},{F:"div",N:"html5-subscribe-button-container"}]}]});g.N(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.RP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Sk,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Da("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Ka);this.Ka();this.hide()},v6=function(a){var b=a.V(),c=g.pE||g.cG?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.X.call(this,{F:"a",Ga:e,X:{href:"{{url}}",target:d?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{F:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{F:"span",N:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-info-bg",W:[{F:"span",N:"ytp-videowall-still-info-content",X:c,W:[{F:"span",N:"ytp-videowall-still-info-title",
qa:"{{title}}"},{F:"span",N:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{F:"span",N:"ytp-videowall-still-info-live",qa:"Live"},{F:"span",N:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{F:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{F:"span",qa:"{{playlist_length}}"},")"]}]},{F:"span",
Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{F:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{F:"span",N:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.mE(this);g.N(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);a.hg(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,
a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.mE(this);g.N(this,this.u);this.Z=a.K("web_rounded_thumbnails");this.I=new g.bo(function(){g.lo(b.element,"ytp-show-tiles")},0);
g.N(this,this.I);var c=new g.X({F:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},W:[g.BL()]});g.N(this,c);c.Ca(this.element);c.Qa("click",this.kV,this);this.table=new g.tL({F:"div",N:"ytp-endscreen-content"});g.N(this,this.table);this.table.Ca(this.element);c=new g.X({F:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},W:[g.CL()]});g.N(this,c);c.Ca(this.element);c.Qa("click",this.jV,this);a.getVideoData().Qe?this.j=new n6(a,!0):this.j=new q6(a);
g.N(this,this.j);g.hO(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},x6=function(a){return g.iO(a.player)&&a.Iy()&&!a.C},m7a=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.jI(e)]},y6=function(a){var b=a.jf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.N(this,this.watchButton);this.watchButton.Ca(this.element);g.VZa(a)&&(this.j=new g.L2(a,g.YN(a)),g.N(this,this.j),this.u=new g.X({F:"div",Ga:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.N(this,this.u),this.j.Ca(this.u.element),this.u.Ca(this.element));a.xb(this.element,this,156914);this.hide()},q7a=function(a){g.NO.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.mE(this);g.N(this,this.listeners);var c=a.V();if(g.tv(g.yG(c))&&!g.eO(a))this.u=!0,this.endScreen=new u6(a,g.YN(a));else{var d;(null==(d=g.YN(a))?0:d.zj())?this.endScreen=new z6(a):n7a(a)?(this.C=!0,o7a(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(this.player)):c.Re?this.endScreen=new l7a(this.player):this.endScreen=new p6(this.player)}g.N(this,this.endScreen);g.hO(this.player,this.endScreen.element,
4);p7a(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.yA("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.S(a,g.zA("endscreen"),function(e){b.onCueRangeExit(e)})},o7a=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Wk&&a.B===b.Qe)return!1;a.j=b.Wk;a.B=b.Qe;return!0},n7a=function(a){a=a.V();
return a.Gc&&!a.Re},p7a=function(a){a.player.xf("endscreen");
var b=a.player.getVideoData();b=new g.wA(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.wA(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.me([b,c])};
g.RS.prototype.mx=g.ba(35,function(a){this.lK!==a&&(this.lK=a,this.Uj())});
g.QS.prototype.kp=g.ba(34,function(a){this.u!==a&&(this.u=a,this.Ay())});
g.RS.prototype.kp=g.ba(33,function(a){this.Vk&&this.Vk.kp(a)});
g.CP.prototype.TA=g.ba(32,function(a){this.mK!==a&&(this.mK=a,this.Kn())});
g.aO.prototype.hq=g.ba(6,function(){return this.app.hq()});
g.EY.prototype.hq=g.ba(5,function(){return this.getVideoData().oM});g.v(m6,g.X);m6.prototype.select=function(){(this.G.Xl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.cz||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.vb(this.element)};
m6.prototype.onClick=function(a){g.nP(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Ax(a)||(this.select(),g.zx(a))}};g.v(n6,g.X);g.k=n6.prototype;g.k.CB=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Um()),o6(this))};
g.k.Aj=function(){return 0<this.B};
g.k.wx=function(){this.Aj()||(this.B=Date.now(),f7a(this),e7a(this.G,h7a(this)),g.po(this.G.getRootNode(),"countdown-running",this.Aj()))};
g.k.It=function(){this.vp();f7a(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.hh(a,"Up next")};
g.k.vp=function(){this.Aj()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.vp()};
g.k.DM=function(a){g.nP(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.vb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.G.Va(a,!0),this.G.vb(a)),this.select())};
g.k.eV=function(){this.G.vb(this.cancelButton.element);g.cO(this.G,!0);this.D&&this.G.Oa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.PU)?void 0:c.command};
g.k.n0=function(a){if(i7a(this)){var b=this.G.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.JM(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.JM(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.JM(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.JM(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.JM(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.JM(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.po(this.element,"ytp-w2w-animate",!0)}};
g.k.dV=function(a){this.G.K("web_autonav_color_transition")&&2!==a&&g.po(this.element,"ytp-w2w-animate",!1)};
g.k.CM=function(){var a=this.G.jf();this.I&&this.rb!==a&&g.wL(this,a);o6(this);this.G.Va(this.container.element,a);this.G.Va(this.cancelButton.element,a);this.G.Va(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.G.Va(this.playButton.element,a)};
g.k.pg=function(a){return 400>a.width||459>a.height};g.v(p6,g.X);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Iy=function(){return!1};
g.k.jf=function(){return!1};
g.k.xQ=function(){return!1};g.v(q6,g.X);g.k=q6.prototype;g.k.rC=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.CB=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.EM=function(){g.wL(this,this.api.jf());this.api.Va(this.element,this.api.jf());this.api.Va(this.Da("ytp-upnext-autoplay-icon"),this.api.jf());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.jf())};
g.k.h1=function(){window.focus();this.rC()};
g.k.wx=function(a){var b=this;this.Aj()||(g.Px("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.S)(),this.j=new g.bo(function(){k7a(b,a)},25),k7a(this,a),e7a(this.api,j7a(this,a)));
g.no(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.Aj=function(){return!!this.j};
g.k.It=function(){this.vp();this.u=(0,g.S)();k7a(this);g.lo(this.element,"ytp-upnext-autoplay-paused")};
g.k.vp=function(){this.Aj()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.rC(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Cf()}),this.B=this.S(this.notification,"click",this.h1),this.C.start())}this.vp();this.api.nextVideo(!1,a)};
g.k.gV=function(a){!g.gh(this.cancelButton.element,g.vx(a))&&g.nP(a,this.api)&&(this.api.jf()&&this.api.vb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.fV=function(){this.api.jf()&&this.cancelButton&&this.api.vb(this.cancelButton.element);g.cO(this.api,!0)};
g.k.W0=function(a){this.api.getPresentingPlayerType();this.show();this.wx(a)};
g.k.X0=function(){this.api.getPresentingPlayerType();this.vp();this.hide()};
g.k.ra=function(){this.vp();this.rC();g.X.prototype.ra.call(this)};g.v(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.C.S(this.player,"appresize",this.by);this.C.S(this.player,"onVideoAreaChange",this.by);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.FM);this.C.S(this.player,"autonavcancel",this.hV);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.cO(this.player,!1);g.iO(this.player)&&this.Iy()&&!this.B?(s6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.wx():3===this.videoData.autonavState&&this.j.It()):(g.cO(this.player,!0),s6(this));this.by()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.It();s6(this)};
g.k.by=function(){var a=this.player.wj(!0,this.player.isFullscreen());s6(this);o6(this.u);g.po(this.element,"ytp-autonav-cancelled-small-mode",this.pg(a));g.po(this.element,"ytp-autonav-cancelled-tiny-mode",this.yD(a));g.po(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Cl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.po(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.jI(this.videoData);b&&(this.j.CB(b),this.j!==this.u&&this.u.CB(b));for(b=0;b<r7a.length;++b){var c=r7a[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.N(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.by()}};
g.k.FM=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.vp(),this.rb&&this.by()):(this.I=!0,this.jf()&&(2===a?this.j.wx():3===a&&this.j.It()))};
g.k.hV=function(a){a?this.FM(1):(this.B=null,this.I=!1)};
g.k.Iy=function(){return 1!==this.videoData.autonavState};
g.k.pg=function(a){return(910>a.width||459>a.height)&&!this.yD(a)&&!(400>=a.width||360>=a.height)};
g.k.yD=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.jf=function(){return this.rb&&g.iO(this.player)&&this.Iy()&&!this.B};
var r7a=[1,3,2,4];g.v(t6,g.X);g.k=t6.prototype;g.k.onClick=function(a){g.oP(this.getVideoUrl(),this.G,a);this.G.vb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.G.getVideoUrl(a,!1,!1,!0);var b=this.G.V();if(g.eG(b)||g.pG(b)){var c={};b.Aa&&g.eG(b)&&g.uN(c,b.loaderUrl);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.tN(c,b);a=g.ji(a,c)}return a};
g.k.Va=function(){this.G.Va(this.element,this.rb&&this.Aa)};
g.k.show=function(){g.X.prototype.show.call(this);this.Va()};
g.k.hide=function(){g.X.prototype.hide.call(this);this.Va()};
g.k.Tb=function(a){g.X.prototype.Tb.call(this,a);this.Va()};g.v(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.j.mx(!0),this.j.kp(!0),this.G.Va(this.element,!0),this.watchButton.Tb(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.j.mx(!1);this.j.kp(!1);this.G.Va(this.element,!1);this.watchButton.Tb(!1)};g.v(l7a,p6);l7a.prototype.Ka=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Sk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(v6,g.X);v6.prototype.select=function(){(this.api.Xl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.cz||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.vb(this.element)};
v6.prototype.onClick=function(a){g.nP(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Ax(a)||(this.select(),g.zx(a))}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.B};g.v(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Sn();this.u.S(this.player,"appresize",this.Sn);this.u.S(this.player,"onVideoAreaChange",this.Sn);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.NF);this.u.S(this.player,"autonavcancel",this.iV);a=this.videoData.autonavState;a!==this.T&&this.NF(a);this.u.S(this.element,"transitionend",this.I2)};
g.k.destroy=function(){g.gz(this.u);g.Ve(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.no(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.Iy=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.rb;p6.prototype.show.call(this);m7a(this);g.no(this.element,"ytp-show-tiles");this.player.V().isMobile?g.eo(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.cO(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.wx():3===this.videoData.autonavState&&this.j.It()):(g.cO(this.player,!0),y6(this));a!==this.rb&&
this.player.Va(this.element,!0)};
g.k.hide=function(){var a=this.rb;p6.prototype.hide.call(this);this.j.It();y6(this);a!==this.rb&&this.player.Va(this.element,!1)};
g.k.I2=function(a){g.vx(a)===this.element&&this.Sn()};
g.k.Sn=function(){var a=m7a(this);if(a.length){g.lo(this.element,"ytp-endscreen-paginate");var b=this.G.wj(!0,this.G.isFullscreen()),c=g.YN(this.G);c&&(c=c.Df()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,w=c<=h-2&&p>=r*n,y=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&y)p-=q*n,f+=2;else if(w)p-=r*n,c+=2;else if(y)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.Ml(b,n,p);g.Cl(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.CB(g.jI(this.videoData));this.j instanceof n6&&o6(this.j);g.po(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,w=0,e&&
h>=c-2&&l>=f-2?w=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(w=2):w=2),q=g.xg(q+this.B,m),0!==w){r=this.stills[d];r||(r=new v6(this.player),this.stills[d]=r,b.appendChild(r.element));y=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+w)/f)-y-4,D=Math.floor(n*(h+w)/c)-z-4;g.Il(r.element,z,y);g.Ml(r.element,D,B);g.Cl(r.element,"transitionDelay",(l+h)/20+"s");g.po(r.element,"ytp-videowall-still-mini",1===w);g.po(r.element,"ytp-videowall-still-large",2<w);this.Z&&(w=Math.max(D,B),g.po(r.element,
"ytp-videowall-still-round-large",256<=w),g.po(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.po(r.element,"ytp-videowall-still-round-small",96>=w));q=a[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),y=g.ko(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(r,q,y),g.eG(w)&&(y=q.Um(),z={},w.Aa&&g.uN(z,w.loaderUrl),y=g.ji(y,g.tN(z,"emb_rel_end")),r.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&r.api.rh(r.element,q));d++}b.ariaBusy="false";g.po(this.element,
"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.eh(c.element),g.Ue(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Sn())};
g.k.jV=function(){this.B+=this.stills.length;this.Sn()};
g.k.kV=function(){this.B-=this.stills.length;this.Sn()};
g.k.xQ=function(){return this.j.Aj()};
g.k.NF=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.vp(),this.rb&&this.Sn()):(this.D=!0,this.rb&&x6(this)&&(2===a?this.j.wx():3===a&&this.j.It()))};
g.k.iV=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Va(this.stills[a].element,!0);this.NF(1)}else this.C=null,this.D=!1;this.Sn()};
g.k.jf=function(){return this.rb&&x6(this)};g.v(z6,p6);z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.po(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.YN(this.player))||c.TA(!0);this.player.Va(this.element,!0);this.watchButton.Tb(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.YN(this.player))||a.TA(!1);this.player.Va(this.element,!1);this.watchButton.Tb(!1)};g.v(q7a,g.NO);g.k=q7a.prototype;g.k.Zt=function(){var a;if((null==(a=g.YN(this.player))?0:a.zj())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.jI(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!n7a(this.player)||c;c=a.Yh||g.pG(a.u);var d=this.player.lz();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.jf=function(){return this.endScreen.jf()};
g.k.ZZ=function(){return this.jf()?this.endScreen.xQ():!1};
g.k.ra=function(){this.player.xf("endscreen");g.NO.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.tb().xe.get("heartbeat"),d=g.jI(a);!d||b.videoId!==d.videoId||a.KP?(this.player.Xl(b.videoId,void 0,void 0,!0,!0,b),c&&c.ED("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.NO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.NO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Zt()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){p7a(this);this.C&&o7a(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.N(this,this.endScreen),g.hO(this.player,this.endScreen.element,4))};g.MO("endscreen",q7a);})(_yt_player);
